FROM golang:1.21.5 as builder

WORKDIR /usr/src/app

COPY . .

RUN go mod init hello-world && \
  go build -o hello-world .

FROM scratch

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

ENTRYPOINT [ "./hello-world" ]