version: "3"

services:
  app:
    image: santosrj/node:latest
    build:
      context: node
      dockerfile: Dockerfile.prod
    container_name: app
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["sh", "-c", "npm ci; node index.js"]
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: santosrj/mysql:latest
    build:
      context: mysql
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    image: santosrj/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    restart: always
    tty: true
    ports:
      - 8080:80
    entrypoint: dockerize -wait tcp://app:3000 -timeout 60s /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
