version: "3"

services:
  app:
    image: santosrj/node:latest
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    tty: true
    entrypoint: node /usr/src/app/index.js
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    ports:
      - 3000:3000

networks:
  node-network:
    driver: bridge
